/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTrace: typeof import('./src/components/form/AddTrace.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataFilter: typeof import('./src/components/filters/DataFilter.vue')['default']
    DatasDisplay: typeof import('./src/components/table/DatasDisplay.vue')['default']
    DatasView: typeof import('./src/components/table/DatasView.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    DetailButton: typeof import('./src/components/button/DetailButton.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Logo: typeof import('./src/components/logo/Logo.vue')['default']
    LogoImg: typeof import('./src/components/logo/LogoImg.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavBar: typeof import('./src/components/navbar/NavBar.vue')['default']
    NumberInput: typeof import('./src/components/input/NumberInput.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Slider: typeof import('primevue/slider')['default']
    StravaCard: typeof import('./src/components/card/StravaCard.vue')['default']
    SuccessToast: typeof import('./src/components/toast/SuccessToast.vue')['default']
    TestTest: typeof import('./src/components/table/testTest.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TextArea: typeof import('./src/components/input/TextArea.vue')['default']
    TextInput: typeof import('./src/components/input/TextInput.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    TracesTable: typeof import('./src/components/table/TracesTable.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
